AWSTemplateFormatVersion: 2010-09-09

Resources:
  Queue:
    Type: AWS::SQS::Queue

  User:
    Type: AWS::IAM::User
    Properties:
      Policies:
        - PolicyName: SQSRead
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                Resource: !GetAtt Queue.Arn

  Credentials:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref User

Outputs:
  SqsQueueUrl:
    Value: !Ref Queue

  AccessKeyId:
    Value: !Ref Credentials

  SecretAccessKey:
    Value: !GetAtt Credentials.SecretAccessKey
